# Presentation Settings

sitename: Public Draft
tagline: Just writing down what I've found.
desc: 調べた事を書いていく。集めた情報をリストアップする。フロントエンダのためのアップデートするブログ。
url: http://publicdraft.studiomohawk.com

# TOOL Settings
ga: UA-61203-19

# System Settings

pygments:    true
markdown:    kramdown
permalink:   pretty
kramdown:
  auto_ids: false
exclude: [LICENSE, README.markdown, jakefile, .rbenv-version, tasks, node_modules, npm-debug.log, package.json, grunt.js, grunt-aws.json]
include: [_includes]
