# Presentation Settings

sitename: Public Draft
tagline: Just writing down what I've found and collected
desc: 調べた事を書いていく。集めた情報をリストアップする。フロントエンダのためのアップデートするブログ。
url: http://publicdraft.studiomohawk.com

# TOOL Settings
ga: UA-61203-19

# System Settings

pygments:    true
markdown:    kramdown
permalink:   pretty
kramdown:
  auto_ids: false
exclude: LICENSE, README.markdown, Rakefile, .rbenv-version, ji.sublime-project, ji.sublime-workspace
include: _includes