# Presentation Settings

sitename: Public Draft
tagline: Outlining and Researching for the Presentation
desc: プレゼン資料づくりの一番はじめのアウトラインとリサーチをログしていきます。
url: http://publicdraft.studiomohawk.com

# TOOL Settings
ga: UA-61203-19

# System Settings
auto: false
server: false
pygments: true
permalink: pretty
markdown: kramdown

kramdown:
  auto_ids: false
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers:
    coderay_tab_width: 2
    coderay_css: class

exclude: [LICENSE, README.markdown, jakefile, .rbenv-version, tasks, node_modules, npm-debug.log, package.json, grunt.js, Gruntfile.js, grunt-aws.json]
include: [_includes]
